### ISSUE TITLE
Add command support

### ISSUE THREAD

**Issue by IntelOrca** [Nick-Lucas/EntryPoint#14]
It would be nice if you could write methods which act as entry points for particular commands, ASP.NET Core style.
Take `git` for example:

`git checkout <ref> [-b -f]`
`git add <path> [-a]`

So you could implement it like:
```cs
[Route("checkout {ref}")]
public int Checkout(string ref, [Option(ShortName = "b")] bool create, [Option(ShortName = "f", LongName = "force")] bool force)
{
    // code...
}

[Route("checkout {path}")]
public int Add([FromRoute]string path, [Switch('a')] bool all)
{

}
```

**Comment by Nick-Lucas** [comment]
Neat idea! It's achievable using the current Api, but the composability of routing to a different class automatically is quite attractive, and should be quite easy to implement, too!

**Comment by IntelOrca** [comment]
@Nick-Lucas Its something I tried to develop a few months ago in my spare time but never finished, so maybe another library like this one can adopt the idea instead.

**Comment by Nick-Lucas** [comment]
I think I will work on this, thanks a lot for the suggestion!
It's very well suited to EntryPoint's intended style, and I was wondering about the best way to approach Commands.

Ideas:

Could define a `BaseCommandClass` and `EntryPointApi.ParseCommand<>()` to enforce a design pattern to this. Would allow for `[Command(name)]` and `[DefaultCommand]` attributes on methods, to compose an entire class of commands. This might be quite a code heavy pattern, but would be easy to maintain and expand in implementations.

Or could `[Command(name)]` attributes inside the `BaseApplicationOptions` class, but this might get messy as options generally wouldn't be used in conjunction with a command, the command would have its own set of options. This also wouldn't be so different from using a single `[Required][Operand(position: 1)]` in a `BaseApplicationOptions` and then switching manually on the resulting value.

Possible EntryPoint Api:
```c#
class CommandClass : BaseCommandClass {
  [DefaultCommand]
  [Command(name)]
  public void StartMyCommand(string[] args) {
    // From here you can start your application down a new logic route, and pass remaining args to a new class
  }

  // Commands & Options & Operands...
}
```

If you have any thoughts/feedback/ideas then let me know! I'm still designing in my head :)

**Comment by IntelOrca** [comment]
My vision was to make it almost the same as ASP.NET CORE, so you would have your commands in a Controller class. I suppose you can either do one of or allow all:

- Base class (`: Controller`)
- Attribute (`[Controller]`)
- Interface with no members (`: IController`)

**Comment by Nick-Lucas** [comment]
Good idea, I'll have a look at my current ASP Core project for ideas

**Comment by IntelOrca** [comment]
@Nick-Lucas https://github.com/IntelOrca/xCLI/blob/master/test/Sample/GitController.cs

I've made my repo public, I've abandoned it now.

**Comment by Nick-Lucas** [comment]
@IntelOrca I've been working on this tonight and have a completed implementation (minus a couple of edge cases) with an update Example project. If you have any feedback I'd love to hear it!

https://github.com/Nick-Lucas/EntryPoint/tree/feature/commands 

Known things to complete:
* Help Generator Support
* Invoking --help will go straight to the default Command, instead of trying to invoke help for the Commands class

**Comment by IntelOrca** [comment]
Looking good!

Do you plan on adding parameter value injection as well?
E.g.
```
        [Command("status {pathspec}")]
        public void Status(string pathspec, [OptionParameter] bool verbose = false)
        {
        }
```

**Comment by Nick-Lucas** [comment]
Can you think of some advantages of this, over the approach I've built?

As it stands a Command Method must match the signature `void MethodName(string[] args)` and I pass on all unused arguments from Command selection.
I see this as more Composable, because a Command is just like the `main` method, and the developer can then parse `ApplicationOptions` or do something else entirely. Whereas your approach would need a new system in EntryPoint and ultimately save a few easy lines of code.

**Comment by Nick-Lucas** [comment]
A halfway point might be to allow `void MethodName(ApplicationOptions options)` and to run `EntryPointApi.Parse` generically, but this is a stretch feature in my mind as it relies on implementations have a 0 parameter constructor, which EntryPoint doesn't enforce

**Comment by IntelOrca** [comment]
My idea was that it works exactly the same as ASP.NET Core controllers which allow parameters to either be URL parameters, query string parameters or services. It's all automatic, you can have what ever parameters you like and it automatically passes the right arguments.

**Comment by Nick-Lucas** [comment]
Yeah it's a good idea for simple cases. I won't rule it out!

My experience of CLIs is a command is rarely a subset of 1-5 arguments though. Usually CLIs get segmented into commands because they're quite complex. In this context a full definitions class would be most appropriate.

I'll create an issue for this and look at it in the future! Closing this thread as I've now implemented the initial Commands Api
https://github.com/Nick-Lucas/EntryPoint/issues/24
