### ISSUE TITLE
Issue with file paths 

### ISSUE THREAD

**Issue by Jsmuk** [Nick-Lucas/EntryPoint#45]
This might be me doing something very silly, so I apologise if that is the case but..

If I try and pass a file path as an operand (like `c:\some\path`) by the time it gets to the method that handles the command the slashes are removed. 
If however I escape them in the input it works as intended. Is there a way around this? Its not *too* much of a big deal for me at the moment (as I am using this primarily on Linux at the moment so I am never encountering `\` as a path separator) but it does mean that dragging and dropping files onto an exe with this setup doesn't work which is a shame.

**Comment by Nick-Lucas** [comment]
Hi @Jsmuk, sorry for the delayed reply.
This is to do with your shell/terminal. `\` is usually considered an escape character and deactivates any functionality the following character may have, and gets stripped.

For instance the command `myapp --mystring="Barry said \"hello\""` would correctly be passed as `Barry said "hello"` to your app, because you've escaped the quotes. Without escaping these the shell's string parsing would fail as your parameter's value would end at `said `.

Behaviour on shells does differ between platforms, and I think on Windows it would behave as you're expecting.
